#version: 0.2
#
#phases:
#  install:
#    runtime-versions:
#      commands:
#        -echo "Installing dependencies..."
#        -sudo apt update
#        -sudo apt install default-jdk
#        -sudo apt install maven
#        # Install any dependencies required for your project here
#
#
#
#  pre_build:
#    commands:
#      - echo "Building Docker image..."
#
#      # Replace 'myproject' with your Docker image name
#
#  build:
#    commands:
#      - echo "Running Maven tests..."
#      - mvn clean install
#      # Replace 'myproject' with your Docker image name
#
#artifacts:
#  files:
#    - '**/*'
version: 0.1

phases:
  install:
    commands:
      - echo installing maven...
      - yum install -y maven
  build:
    commands:
      - echo Build completed on `date`
      - cd Walgreens
      - mvn clean install -X

artifacts:
  files:
    - '**/*'