version: 0.2

phases:
#  install:
#    runtime-versions:
#      docker: 19
#    commands:
#      - echo "Installing dependencies..."
#      # Install any dependencies required for your project here
#
  pre_build:
    commands:
      - echo "Building Docker image..."
      - docker build -t aws/codebuild/standard:7.0  .
      # Replace 'myproject' with your Docker image name

  build:
    commands:
      - echo "Running Maven tests..."
      - docker run --rm MyprojectNabil mvn test
      # Replace 'myproject' with your Docker image name

artifacts:
  files:
    - '**/*'
