version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
      commands:
        - echo "Installing dependencies..."
          - apt-get update -y
          - apt-get install -y software-properties-common
          - add-apt-repository ppa:openjdk-r/ppa
          - apt-get update -y
          - apt-get install -y openjdk-8-jdk
          - apt-get install -y maven
        # Install any dependencies required for your project here



  pre_build:
    commands:
      - echo "Building Docker image..."

      # Replace 'myproject' with your Docker image name

  build:
    commands:
      - echo "Running Maven tests..."
      - mvn clean install
      # Replace 'myproject' with your Docker image name

artifacts:
  files:
    - '**/*'
